#!/usr/bin/env node
 // -*- mode: javascript; -*-

"use strict";

var program = require('commander');
var rest = require('restler');
var tools = require('./tools');
var config = require('./config');

console.log("Running developer console...");

tools.doForMyself(function(data) {
    tools.subscribe(data.authId, data.authKey, "/provider/" + data.providerCompanyId + "/all-things", config.baseWsUrl);
});
