#!/usr/bin/env node
// -*- mode: javascript; -*-

"use strict";

var program = require('commander');
var rest = require('restler');

var base = "http://api.rapifire.com/api/v1/things/";

program
  .command("create <name> <product>")
  .description("Create new thingt")
  .action(function(name, product, opts) {
    // get product by name
    // get product id
    // use it in thing creation
    console.log("Creating new thing named:", name, "product:", product);
  });

program.parse(process.argv);
if (!program.args.length) {
  program.help();
}
