#!/usr/bin/env node
// -*- mode: javascript; -*-

"use strict";

var program = require('commander');
var rest = require('restler');
var tools = require('./tools');
var config = require('./config');

var base = config.baseApiUrl + "/things/";
var getProductByNameUrl = config.baseApiUrl + "/products/?name=";
var getUserByNameUrl = config.baseApiUrl + "/users/?username=";

program
  .command("create <name> <product>")
  .description("Create new thing")
  .action(function(name, product, opts) {
      console.log("Creating new thing named " + name + " for product " + product);

      tools.doForProductName(product, function(productId){
          rest.postJson(base, {productId: productId, name:  name}, tools.getAuthObj())
              .on('success', function(data, response) {
                  console.log("New thing created: " + JSON.stringify(data));
              })
              .on('fail', tools.failureHandler);
        })
  });


program
  .command("update <name> <product> <newName> <newProductName> [userName]")
  .description("Update thing entry")
  .action(function(name, product, newName, newProductName, userName, opts){
    tools.doForThingName(name, product, function(thingId, oldProductId){
      tools.doForProductName(newProductName, function(productId){
        var updateJson = {
          name : newName,
          productId : productId
        }

        var updateThing = function(json){
          rest.putJson(base + thingId, json, tools.getAuthObj())
          .on('success', function(data, response){
            console.log("Thing updated.");
          })
          .on('fail', tools.failureHandler);
        }

        if(userName && userName.length > 0) {
          tools.doForUserName(userName, function(userId){
            updateJson.userId = userId;
            updateThing(updateJson);
          });
        } else {
          updateThing(updateJson);
        }
      });
    });
  });


program.parse(process.argv);
if (!program.args.length) {
  program.help();
}
