#!/usr/bin/env node
// -*- mode: javascript; -*-

"use strict";

var program = require('commander');
var rest = require('restler');
var tools = require('./tools');
var config = require('./config');


var base = config.baseApiUrl + "/users/";

program
  .command("list")
  .description("List all users")
  .action(function(opts) {
    rest.get(base, tools.getAuthObj())
      .on('success', function(data , response) {
      	tools.printJsonArray(data);
      }).on('fail', tools.failureHandler);
  });	

program
  .command("show <login>")
  .description("Returns single user.")
  .action(function(login, opts){
    doForUserName(login, function(userId){
      rest.get(base + userId, tools.getAuthObj())
        .on('success', function(data, response){
          tools.printJson(data);
        })
        .on('fail', tools.failureHandler);
    });
  });

program
  .command("create <login> <password> <name> [description]")
  .description("Create new user")
  .action(function(login, password, name, description, opts) {
    var description = description ? description : 'This user is created by rapifire-cli';
    var newUserData = {
      login: login, 
      password: password, 
      name: name, 
      description: description
    }

    rest.postJson(base, newUserData, tools.getAuthObj())
      .on('success', function(data, response) {
    	 console.log("User " + name + " created.");
      }).on('fail', tools.failureHandler);
  });

program
  .command("update <login> <name> <description> [password]]")
  .description("Update user name, description and optionally password")
  .action(function(login, name, description, password, opts) {
    var updateJson = {
      "name" : name,
      "description" : description,
      "password" : password
    }

    doForUserName(login, function(userId){
      rest.putJson(base + userId, updateJson, tools.getAuthObj())
        .on('success', function(data, response){
          console.log("User " + name + " updated.");
        })
        .on('fail', tools.failureHandler);
    })
  });

program
  .command("meta <login>")
  .description("List all metadata for user")
  .action(function(login, opts){
    var config = tools.readConfig();

    rest.get(base + '?username=' + login, {username: config.username, password: config.password})
      .on('success', function(data, response){
        if(data.length != 1) return;
        var userId = data[0].id;

        rest.get(base + userId + '/meta', {username: config.username, password: config.password})
          .on('success', function(data, response){
            tools.printJsonArray(data);
          }).on('fail', tools.failureHandler);

      }).on('fail', tools.failureHandler);
  });

function doForUserName(username, callback) {
  rest.get(base + "?username=" + username, tools.getAuthObj())
    .on('success', function(data, response) {
      if(data.length != 1){
        process.exit(1);
      }
      var userId = data[0].id;
      callback(userId);
    }).on('fail', tools.failureHandler);
}

program.parse(process.argv);
if (!program.args.length) {
  program.help();
}
