#!/usr/bin/env node
 // -*- mode: javascript; -*-

"use strict";

var program = require('commander');
var rest = require('restler');
var tools = require('./tools');
var config = require('./config');

console.log("Running developer console...");

tools.doForMyself(function(authId, authKey, providerCompanyId) {
  tools.subscribe(authId, authKey, "/provider/" + providerCompanyId + "/all-things", config.baseWsUrl);
});
