#!/usr/bin/env node
// -*- mode: javascript; -*-

"use strict";

var program = require('commander');
var rest = require('restler');
var tools = require('./tools');
var config = require('./config');

var WebSocket = require('ws');

var getThingByName = config.baseApiUrl + "/things/?query=";
var websocketUrl = config.baseWsUrl;

program
    .command("as <name>")
    .description("Subscribe as a Thing to it's command channel")
    .action(function(name, opts) {
        console.log("Subscribing as " + name + " to it's command channel.");

        var config = tools.readConfig();
        rest.get(getThingByName + name, {username: config.username, password: config.password})
            .on('complete', function(data, response) {

                var thing = null;
                for (var i = 0; i < data.length; i++) {
                    if (data[i].name == name) {
                        thing = data[i];
                        break;
                    }
                }
                if (thing == null) {
                    console.log("Thing not found");
                    process.exit(1);
                }

                console.log(thing);
                doSubscribe(thing.thingId, thing.thingToken, "/" + thing.thingId + "/commands", websocketUrl);

            })
            .on('fail', tools.failureHandler);

    });


function doSubscribe(authId, authKey, channel, url) {
    var init = {
      "operation": "init",
      "data": {
          "authId": authId,
          "authKey": authKey,
      }
    };

    var packet = {
        "operation": "subscribe",
        "data": {
            "channel": channel
        }
    };

    var ws = new WebSocket(url);

    console.log(ws);
    ws.on('message', function(data) {
      console.log("<- " + data);
    });

    ws.on('close', function close() {
      process.exit(0);
      ws = null;
    });

    ws.on('open', function() {
        console.log("-> " + JSON.stringify(init));
        ws.send(JSON.stringify(init));

        console.log("-> " + JSON.stringify(packet));
        ws.send(JSON.stringify(packet));
    });


}

program.parse(process.argv);
if (!program.args.length) {
  program.help();
}
